version: '3.6'
services:   
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms${NODE_MEM} -Xmx${NODE_MEM}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
       soft: 65536
       hard: 65536
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ES_DATA_PATH_1}:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    logging:
      driver: "json-file"
      options:
        max-size: "2048k"
        max-file: "5"

